### PR TITLE
Align shortcuts text

### PR DESCRIPTION
**Pull request by patmellon**
This PR aligns the "Shortcuts" nav text with the "Edit on GitHub" text. Preview link: https://5e5ec1d05d76fe0198158cb4--shiftlab-pytorch-tutorials.netlify.com/

Updated preview link 4/7/21: https://606db70b37c4a51229e6e0de--shiftlab-pytorch-docs.netlify.app/

### CODE REVIEW

**Comment by brianjo** [comment]
@patmellon Pat, I started going back through these and I missed this one, can you rebase it and add me and I'll get it merged? Thanks!

**Comment by brianjo** [comment]
@patmellon Hey Pat, can you rebase this and I'll merge it. Sorry I missed it earlier.

**Comment by patmellon** [comment]
@brianjo Sure thing. I'll rebase it and make sure that everything still looks good before pushing it up.

**Comment by brianjo** [comment]
Thanks Pat!

**Comment by patmellon** [comment]
Updated preview: https://606db70b37c4a51229e6e0de--shiftlab-pytorch-docs.netlify.app/

**Pull request merged**
