### PR TITLE
Fixes #108 visual issue with nav links

### LINKED ISSUE #108: Visual issue with bullet points in left navigation
This is an old issue, but it would be nice if we could fix. The bullets seem to be aligned bottom instead of middle in the left navigation.  @Bgreen23 

Screenshot from 2021-04-07 16-07-32

### PR DESCRIPTION
**Pull request by ranman**
fixes #108 by adding a negative 10% top positioning to the current link item

### CODE REVIEW

**Comment by brianjo** [comment]
Removed: I had tested the wrong PR.

**Comment by ranman** [comment]
Could you inspect the :before element and let me know the CSS properties it has? It should have top: -10%

**Comment by ranman** [comment]
This is what I see on mac osx , latest chrome after running `make build` and then `python -m http.server --directory build/html/`
Screen Shot 2021-04-19 at 12 31 40 PM

**Comment by brianjo** [comment]
Sorry, I had installed the theme from the wrong PR earlier. That said, this PR isn't working for me at all. I'm getting a corrupted render after the build. 

Steps: 
First tested with requirements.txt. No render issues. 
```
git clone git@github.com:pytorch/pytorch_sphinx_theme.git
cd pytorch_sphinx_theme
git fetch origin pull/113/head:pr113
git checkout pr113
cd ..
pip install -e pytorch_sphinx_theme/

cd into pytorch/docs
make clean
make html
cd build/html
python -m http.server
```
Maybe somebody else could give this a try. @holly1238?

**Comment by brianjo** [comment]
@holly1238 Tested this and it's working for her, so thanks so much for that Holly! I'll go ahead and merge this. Thanks for the PR @ranman!

**Pull request merged**
