### PR TITLE
Include build files for expand/collapse

### PR DESCRIPTION
**Pull request by Bgreen23**
This PR adds the build files for Expand/Collapse

### UPDATE

This PR has been updated with the functionality to "save" the expand/collapsed state between pages/page reload while the session is active. You'll be able to see this working in the preview if you visit the session storage using the Chrome DevTools([Instructions ](https://developers.google.com/web/tools/chrome-devtools/storage/sessionstorage))

Docs Preview: https://60403da2607dd52f1108d84f--shiftlab-pytorch-docs.netlify.app/

### CODE REVIEW

**Comment by Bgreen23** [comment]
I'm working on adding the ability to keep items expanded/collapsed on page view to this PR. As is, this PR fixes the current [issue](https://github.com/pytorch/pytorch_sphinx_theme/issues/98) with the expand/collapse.

**Comment by brianjo** [comment]
@Bgreen23 Just let me know when you're ready on this. Thanks!

**Comment by Bgreen23** [comment]
Hey @brianjo the PR has been updated with the functionality to "save" the expand/collapsed state between pages/page reload while the session is active. I wasn't able to generate the files locally to get a preview running for the tutorials, but I  generated a preview for the docs for how that would look/function. In the preview "Package Reference" is closed with the `collapsedSections` array, and if you open that section or close the "Notes" section and refresh/go to another page then they'll stay in the same state. This is accomplished using `sessionStorage`. You'll be able to see this working if you visit the session storage using the Chrome DevTools([Instructions ](https://developers.google.com/web/tools/chrome-devtools/storage/sessionstorage))

Docs Preview: https://60403da2607dd52f1108d84f--shiftlab-pytorch-docs.netlify.app/

Screen Shot 2021-03-03 at 9 33 17 PM

**Comment by brianjo** [comment]
Great! Thanks Brandon!

**Pull request merged**
