### PR TITLE
Expand Sidebar

### PR DESCRIPTION
**Pull request by Bgreen23**
This PR adds the expand/hide toggle to left nav menu items on the Docs & Tutorials.

### CODE REVIEW

**Comment by brianjo** [comment]
Hey @Bgreen23, before I merge this, is there a way for me to have a group stay open by default?

**Comment by Bgreen23** [comment]
Hey @brianjo, I'm currently working on an approach to have configurable expanded/collapsed groups. I expect to update this PR with those changes by 1/22

**Comment by brianjo** [comment]
> Hey @brianjo, I'm currently working on an approach to have configurable expanded/collapsed groups. I expect to update this PR with those changes by 1/22

Awesome. If possible, I think it would be best if expand was the default and we added code to specify collapse to individual sections. That would make it easier to configure the current content without disrupting the way the users are used to viewing it. I'm going to hold off on this PR then and we'll merge your new one. Thanks!

**Comment by patmellon** [comment]
@brianjo Next week we'll open another PR with the ability to configure collapsed sections. We're going to add an array to both of the project layout files 

- https://github.com/pytorch/pytorch/blob/master/docs/source/_templates/layout.html
- https://github.com/pytorch/tutorials/blob/master/_templates/layout.html

The code will look something like 

```
<script type="text/javascript">
    var collapsedSections = ['Package Reference'];
 </script>
```

Whenever you want a menu section to collapse as its default behavior, you can add the menu name to the array for that project. All other sections will remain expanded by default.

**Pull request merged**
