### PR TITLE
Allow images to define width

### LINKED ISSUE #140: Unable to define width of image
I'm using pytorch_sphinx_theme for a PyTorch domain library I'm developing. When I try to add a link to an external SVG image (like a badge) it seems that I'm unable to control the width of the image. For example:
```rst
.. image:: https://colab.research.google.com/assets/colab-badge.svg
   :width: 200
```
When I build this, no matter what width I specify, it is always 100%. The HTML is being rendered correctly:
```html
<a class="reference internal image-reference" href="https://colab.research.google.com/assets/colab-badge.svg"><img alt="https://colab.research.google.com/assets/colab-badge.svg" src="https://colab.research.google.com/assets/colab-badge.svg" width="200" /></a>
```
but because of [these lines of CSS](https://github.com/pytorch/pytorch_sphinx_theme/blob/master/pytorch_sphinx_theme/static/css/theme.css#L10252,L10254):
```css
article.pytorch-article img {
  width: 100%;
}
```
the width is being overridden. If I remove that section from the CSS it behaves as expected.

Is this section actually needed for something, or should I submit a PR to remove it?

P.S. @calebrob6 is the one who actually found the offending lines of CSS.

### PR DESCRIPTION
**Pull request by adamjstewart**
Fixes #140. See #140 for details.

@calebrob6

### CODE REVIEW

**Comment by adamjstewart** [comment]
@brianjo can you review this?

**Comment by adamjstewart** [comment]
@patmellon can you review this?

**Comment by ain-soph** [comment]
As far as I know, this repo is seldom maintained...

You may propose the issue in pytorch main repo to gain more attention, if you think the modification is worth review asap.

I think this PR worth review, since the previous theme can't change image width. (but maybe not your another PR about footer modification, which is really minor.)

**Comment by brianjo** [comment]
Adam, could you post a before and after screen so I can see what the difference is? I'll take a look on Monday and merge it after I run some tests. Thanks for the contribution!

**Comment by ain-soph** [comment]
@brianjo 

I've tested this modification. Before this PR, all images are with 100% width, even you have written in the rst file with
```rst
.. image:: ./XXX.jpg
    :width: 60%
```
The generated html img tag is corrected with 
```html
<img alt="XXX.jpg" src="XXX.jpg" width="60%">
```
But it won't take effect because the there's style with `width: 100%` in the css file.

```css
article.pytorch-article img {
  width: 100%;
}
```

Removing this style makes it work again. (You could see that from his changes)

**Comment by adamjstewart** [comment]
> As far as I know, this repo is seldom maintained...

That's unfortunate, as I think this is a great Sphinx theme and a lot of projects rely on it, including [my own](https://torchgeo.readthedocs.io/). I don't think I know enough about web dev to help maintain this project, but if there's anything else I can do to help let me know. I would love to see this theme install correctly without having to copy it into the root of the documentation.

**Comment by brianjo** [comment]
It’s not really that. It’s a custom fork of the read the docs theme especially made for the PyTorch sites, so we usually don’t update it unless we see a problem. It’s a really nice theme though and I think that it would be great if somebody forked it and created a new, generic theme that could be maintained by the community.
________________________________

**Comment by ain-soph** [comment]
I'm currently working on my [trojanzoo_sphinx_theme](https://github.com/ain-soph/trojanzoo_sphinx_theme), which removes all pytorch-related items, and making it a pure doc theme. You can customized most things in your sphinx workspace, including logo images and permalinks (home, docs, other docs, and github_url) inside.  

I've fixed many bugs I've seen, and propose PR to pytorch_sphinx_theme if possible. And I also add some minor visual changes. You may take a look if you are interested.  

Example:

A demo: https://ain-soph.github.io/trojanzoo_sphinx_theme/  
My python plotting package: https://ain-soph.github.io/alpsplot/

**Comment by brianjo** [comment]
Oh that’s awesome. I’ll be sure to share if someone asks about a generic version.
________________________________

**Comment by adamjstewart** [comment]
This looks great! I probably won't switch to this until the rest of the PyTorch community switches though. Trying to maintain some semblance of uniformity in docs. Is the PyTorch community willing to switch to this? It seems pointless to have two repos if we have to submit bug fixes to both.

**Comment by ain-soph** [comment]
> This looks great! I probably won't switch to this until the rest of the PyTorch community switches though. Trying to maintain some semblance of uniformity in docs. Is the PyTorch community willing to switch to this? It seems pointless to have two repos if we have to submit bug fixes to both.

I'm not expecting to this though. Currently `pytorch_sphinx_theme` has a lot of items specially designed for pytorch, including additional social links and other links in `layout.html`.  
A possible solution would be to put the special `layout.html` in `/docs` of `pytorch` and `tutorial` repos (which they already have for some additional minor modification), and make `pytorch_sphinx_theme` as a generic theme.

**Comment by adamjstewart** [comment]
> A possible solution would be to put the special layout.html in /docs of pytorch and tutorial repos (which they already have for some additional minor modification), and make pytorch_sphinx_theme as a generic theme.

Yes, this is exactly what I'm hoping for. Since my project is also a PyTorch domain library, I would like to keep my docs consistent with the other ones. I think this also represents a best case for the PyTorch devs too since they won't have to maintain this repo anymore.

**Comment by adamjstewart** [comment]
Closing this as it seems that this repo is not maintained. We're starting to seriously consider the `trojanzoo_sphinx_theme` since it's actually maintained.

**Pull request closed without merging**
